# Generated by Django 6.1 on 2026-09-16 14:28

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Content')),
                ('changes', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Changes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_wiki_article_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='app_wiki/%Y/%m/%d')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wiki.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_wiki_file_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('file', models.ImageField(upload_to='app_wiki/%Y/%m/%d')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wiki.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_wiki_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Struct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortorder', models.IntegerField(default=1000)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_wiki.struct', verbose_name='Parents articles')),
            ],
            options={
                'ordering': ('sortorder',),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='struct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wiki.struct'),
        ),
    ]
